`timescale 1ns/1ps
//////////////////////////////////////////////////////////////////////////////////
// Module: miner_top
// Description:
//   Top-level module for the Bitcoin miner. It integrates the following:
//     - nonce_counter: Generates the dynamic nonce.
//     - block_header: Constructs an 80-byte block header using the nonce.
//     - double_sha: Performs double SHA‑256 hashing on the full block header.
//     - hash_comparator: Compares the resulting hash to a target value.
//   When a valid solution is found (hash < target), it outputs the solution flag,
//   the computed hash, and the nonce used.
// Ports:
//   - clk, reset: Clock and asynchronous reset.
//   - start: Start signal to initiate hashing.
//   - target: 256-bit target threshold; a valid solution is indicated when 
//             hash < target.
//   - solution_found: Asserted when a valid hash is computed.
//   - hash_out: Final 256-bit double SHA‑256 hash.
//   - nonce_out: Nonce value used to produce the computed hash.
//////////////////////////////////////////////////////////////////////////////////

module miner_top (
    input  logic         clk,
    input  logic         reset,
    input  logic         start,
    input  logic [255:0] target,
    output logic         solution_found,
    output logic [255:0] hash_out,
    output logic [31:0]  nonce_out
);

    // Internal signals
    logic [31:0]   nonce;     // Dynamic nonce from the nonce counter.
    logic [639:0]  header;    // Full block header generated by block_header.
    logic          ip_done;   // Trigger signal from the double SHA block.

    // Instantiate the nonce counter.
    nonce_counter u_nonce_counter (
        .clk(clk),
        .reset(reset),
        .nonce(nonce)
    );
    
    // Instantiate the block header generator.
    block_header u_block_header (
        .nonce(nonce),
        .header(header)
    );
    
    // Instantiate the double SHA-256 block.
    // This module implements the first and second SHA-256 rounds in sequence.
    // It accepts the full block header as its input message.
    double_sha256 u_double_sha256 (
        .clk(clk),
        .reset(reset),,
        .message(header),
        .trigger(ip_done),
        .hash_out(hash_out)
    );
    
    // Instantiate the hash comparator to verify if the computed hash meets
    // the mining target.
    hash_comparator u_hash_comparator (
        .hash(hash_out),
        .target(target),
        .valid_solution(solution_found)
    );
    
    // Output the nonce used.
    assign nonce_out = nonce;

endmodule
